-- =============================================================================
-- TABLE: REF_CORRECTION_TOKEN
-- =============================================================================
-- Secure one-time tokens for applicant reference correction links.
-- Generated by admin, consumed when applicant submits corrections.
-- Tokens expire after 72 hours and are single-use.
-- =============================================================================

CREATE TABLE ref_correction_token (
    token_id            NUMBER GENERATED ALWAYS AS IDENTITY,
    token               VARCHAR2(64)   NOT NULL,
    job_application_id  NUMBER         NOT NULL,
    candidate_email     VARCHAR2(500),              -- email link was sent to (NULL if copy-link only)
    requested_by        VARCHAR2(240)  NOT NULL,    -- APEX user who generated the link
    requested_on        TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    expires_on          TIMESTAMP(6)   NOT NULL,    -- requested_on + 72 hours
    used_yn             VARCHAR2(1)    DEFAULT 'N' NOT NULL,
    used_on             TIMESTAMP(6),
    --
    CONSTRAINT ref_correction_token_pk PRIMARY KEY (token_id),
    CONSTRAINT ref_correction_token_uk UNIQUE (token),
    CONSTRAINT ref_correction_token_used_ck CHECK (used_yn IN ('Y','N'))
);

CREATE INDEX ref_correction_token_n1 ON ref_correction_token (job_application_id, used_yn);
CREATE INDEX ref_correction_token_n2 ON ref_correction_token (expires_on);

COMMENT ON TABLE  ref_correction_token IS 'One-time tokens for applicant reference correction links';
COMMENT ON COLUMN ref_correction_token.token IS '64-char hex string from dual SYS_GUID concatenation';
COMMENT ON COLUMN ref_correction_token.candidate_email IS 'Email address link was sent to (NULL if admin copied link manually)';
COMMENT ON COLUMN ref_correction_token.requested_by IS 'APEX user who generated the correction link';
COMMENT ON COLUMN ref_correction_token.expires_on IS 'Token valid until this timestamp (72 hours from creation)';
COMMENT ON COLUMN ref_correction_token.used_yn IS 'Y after applicant submits corrections, preventing reuse';
