CREATE TABLE FBX_QSTNR_ANSWER
(
    QSTN_ANSWER_ID        NUMBER,
    SEQ_NUM               NUMBER,
    SCORE                 NUMBER,
    ANSWER_LONG_TEXT      VARCHAR2(4000),
    ANSWER_SHORT_TEXT     VARCHAR2(400),
    RESPONSE_FEEDBACK     VARCHAR2(4000),
    LAST_UPDATE_DATE_TS   TIMESTAMP(6),
    LAST_EXTRACT_RUN_ID   VARCHAR2(64),
    LAST_EXTRACT_RUN_TS   TIMESTAMP(6),
    CONSTRAINT FBX_QSTNR_ANSWER_PK PRIMARY KEY (QSTN_ANSWER_ID)
);
